services:
  main:
    build:
      context: "${HUTCH_IMAGES_DIR}/${HUTCH_BUILD}"
    image: "${HUTCH_IMAGE}"
    stdin_open: true
    tty: true
    user: "${HUTCH_UID}:${HUTCH_GID}"
    environment:
      - HOME=/home/user
    group_add:
      - "${HUTCH_DOCKER_GID}"
    volumes:
      - profile_home:/home/user
      - "${HUTCH_WORKSPACE}:/workspace"
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace

volumes:
  profile_home:
    name: "${HUTCH_PROFILE}_home"
