services:
  main:
    build:
      context: "${HUTCH_IMAGES_DIR}/${HUTCH_BUILD}"
    image: "${HUTCH_IMAGE}"
    stdin_open: true
    tty: true
    hostname: "${HUTCH_PROFILE}"
    labels:
      hutch.profile: "${HUTCH_PROFILE}"
    environment:
      - HUTCH_USER
      - HUTCH_UID
      - HUTCH_GID
      - HUTCH_DOCKER_GID
    volumes:
      - profile_home:/home/user
      - "${HUTCH_WORKSPACE}:/workspace"
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace

volumes:
  profile_home:
    name: "${HUTCH_PROFILE}_home"
