services:
  main:
    build:
      context: "${HUTCH_IMAGES_DIR}"
      dockerfile: "${HUTCH_BUILD}/Dockerfile"
    image: "${HUTCH_IMAGE}"
    stdin_open: true
    tty: true
    hostname: "${HUTCH_PROFILE}"
    labels:
      hutch.profile: "${HUTCH_PROFILE}"
    environment:
      - HUTCH_USER
      - HUTCH_UID
      - HUTCH_GID
      - HUTCH_DOCKER_GID
      - HUTCH_WORKSPACE
      - TERM
      - COLORTERM
    volumes:
      - profile_home:/home/user
      - "${HUTCH_WORKSPACE}:${HUTCH_WORKSPACE}"
    working_dir: "${HUTCH_WORKSPACE}"

volumes:
  profile_home:
    name: "${HUTCH_PROFILE}_home"
